version: "3.9"
services:

  db:
    container_name: postgres_container
    image: postgres:latest
    env_file:
      db.env
    volumes:
      - ./db/initDB:/docker-entrypoint-initdb.d
      - /home/morozvol/GolandProjects:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G

  auth_service:
    container_name: auth_service
    image: morozvol/auth_service:latest
    ports:
      - 8050:8050
    env_file:
      .env
    depends_on:
      - db
